server:
  port: 8070  # 如果不设置，默认为8080

spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test #url
    username: root  #用户名
    password: cheetah2019  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
mybatis:
  mapper-locations: classpath:mapper/*.xml   # 配置映射文件
  type-aliases-package: ccom.sunlab.helloweb.bean  # 配置实体类